export const product_category_seed = [
  { productId: 4, categoryId: 2, subCategoryId: 17 },
  { productId: 2, categoryId: 2, subCategoryId: 13 },
  { productId: 1, categoryId: 2, subCategoryId: 13 },
  { productId: 3, categoryId: 4, subCategoryId: 20 },
  { productId: 5, categoryId: 1, subCategoryId: 4 },
  { productId: 6, categoryId: 3, subCategoryId: 7 },
  { productId: 7, categoryId: 2, subCategoryId: 13 },
  { productId: 8, categoryId: 4, subCategoryId: 18 },
  { productId: 9, categoryId: 8, subCategoryId: null },
  { productId: 11, categoryId: 2, subCategoryId: 15 },
  { productId: 13, categoryId: 2, subCategoryId: 13 },
  { productId: 16, categoryId: 9, subCategoryId: null },
  { productId: 18, categoryId: 7, subCategoryId: 17 },
  { productId: 10, categoryId: 6, subCategoryId: 5 },
  { productId: 12, categoryId: 2, subCategoryId: 17 },
  { productId: 15, categoryId: 1, subCategoryId: 4 },
  { productId: 17, categoryId: 2, subCategoryId: 17 },
  { productId: 19, categoryId: 2, subCategoryId: 13 },
  { productId: 20, categoryId: 1, subCategoryId: 7 },
  { productId: 14, categoryId: 2, subCategoryId: 17 },
];

export const stock_seed = [
  { productId: 4, sizeId: 1, colorId: 14, quantity: 50 },
  { productId: 4, sizeId: 1, colorId: 15, quantity: 30 },
  { productId: 2, sizeId: 1, colorId: 1, quantity: 100 },
  { productId: 1, sizeId: 8, colorId: 1, quantity: 50 },
  { productId: 1, sizeId: 9, colorId: 1, quantity: 90 },
  { productId: 3, sizeId: 1, colorId: 11, quantity: 150 },
  { productId: 5, sizeId: 3, colorId: 16, quantity: 20 },
  { productId: 5, sizeId: 4, colorId: 16, quantity: 30 },
  { productId: 5, sizeId: 5, colorId: 16, quantity: 15 },
  { productId: 5, sizeId: 3, colorId: 15, quantity: 25 },
  { productId: 5, sizeId: 5, colorId: 15, quantity: 40 },
  { productId: 5, sizeId: 6, colorId: 15, quantity: 35 },
  { productId: 6, sizeId: 1, colorId: 11, quantity: 20 },
  { productId: 7, sizeId: 1, colorId: 1, quantity: 29 },
  { productId: 8, sizeId: 3, colorId: 11, quantity: 32 },
  { productId: 8, sizeId: 4, colorId: 11, quantity: 32 },
  { productId: 8, sizeId: 5, colorId: 11, quantity: 32 },
  { productId: 9, sizeId: 10, colorId: 17, quantity: 45 },
  { productId: 9, sizeId: 11, colorId: 17, quantity: 50 },
  { productId: 11, sizeId: 1, colorId: 1, quantity: 60 },
  { productId: 13, sizeId: 8, colorId: 1, quantity: 25 },
  { productId: 13, sizeId: 9, colorId: 1, quantity: 35 },
  { productId: 13, sizeId: 8, colorId: 2, quantity: 15 },
  { productId: 13, sizeId: 9, colorId: 2, quantity: 15 },
  { productId: 16, sizeId: 10, colorId: 17, quantity: 48 },
  { productId: 18, sizeId: 1, colorId: 3, quantity: 60 },
  { productId: 18, sizeId: 1, colorId: 4, quantity: 55 },
  { productId: 10, sizeId: 3, colorId: 7, quantity: 35 },
  { productId: 10, sizeId: 4, colorId: 7, quantity: 18 },
  { productId: 10, sizeId: 5, colorId: 7, quantity: 22 },
  { productId: 10, sizeId: 6, colorId: 7, quantity: 25 },
  { productId: 10, sizeId: 7, colorId: 7, quantity: 29 },
  { productId: 10, sizeId: 3, colorId: 2, quantity: 35 },
  { productId: 10, sizeId: 4, colorId: 2, quantity: 18 },
  { productId: 10, sizeId: 5, colorId: 2, quantity: 22 },
  { productId: 10, sizeId: 6, colorId: 2, quantity: 25 },
  { productId: 10, sizeId: 7, colorId: 2, quantity: 29 },
  { productId: 10, sizeId: 3, colorId: 15, quantity: 35 },
  { productId: 10, sizeId: 4, colorId: 15, quantity: 18 },
  { productId: 10, sizeId: 5, colorId: 15, quantity: 22 },
  { productId: 10, sizeId: 6, colorId: 15, quantity: 25 },
  { productId: 10, sizeId: 7, colorId: 15, quantity: 29 },
  { productId: 12, sizeId: 1, colorId: 4, quantity: 45 },
  { productId: 12, sizeId: 1, colorId: 9, quantity: 42 },
  { productId: 15, sizeId: 5, colorId: 8, quantity: 30 },
  { productId: 15, sizeId: 6, colorId: 8, quantity: 35 },
  { productId: 15, sizeId: 7, colorId: 8, quantity: 15 },
  { productId: 15, sizeId: 5, colorId: 10, quantity: 30 },
  { productId: 15, sizeId: 6, colorId: 10, quantity: 35 },
  { productId: 15, sizeId: 7, colorId: 10, quantity: 15 },
  { productId: 17, sizeId: 1, colorId: 1, quantity: 50 },
  { productId: 17, sizeId: 1, colorId: 2, quantity: 50 },
  { productId: 19, sizeId: 1, colorId: 1, quantity: 20 },
  { productId: 20, sizeId: 10, colorId: 1, quantity: 30 },
  { productId: 20, sizeId: 11, colorId: 1, quantity: 40 },
  { productId: 14, sizeId: 1, colorId: 1, quantity: 20 },
  { productId: 14, sizeId: 1, colorId: 2, quantity: 25 },
  { productId: 14, sizeId: 1, colorId: 6, quantity: 15 },
];

export const rating_seed = [
  { userId: 2, productId: 4, ratingId: 5 },
  { userId: 3, productId: 4, ratingId: 4 },
  { userId: 4, productId: 4, ratingId: 5 },
  { userId: 5, productId: 4, ratingId: 5 },
  { userId: 6, productId: 4, ratingId: 3 },
  { userId: 7, productId: 2, ratingId: 4 },
  { userId: 8, productId: 2, ratingId: 4 },
  { userId: 9, productId: 2, ratingId: 4 },
  { userId: 10, productId: 2, ratingId: 3 },
  { userId: 11, productId: 2, ratingId: 3 },
  { userId: 5, productId: 1, ratingId: 4 },
  { userId: 6, productId: 1, ratingId: 4 },
  { userId: 7, productId: 1, ratingId: 4 },
  { userId: 8, productId: 1, ratingId: 2 },
  { userId: 9, productId: 1, ratingId: 3 },
  { userId: 10, productId: 1, ratingId: 1 },
  { userId: 11, productId: 1, ratingId: 1 },
  { userId: 2, productId: 3, ratingId: 3 },
  { userId: 3, productId: 3, ratingId: 4 },
  { userId: 4, productId: 3, ratingId: 4 },
  { userId: 19, productId: 3, ratingId: 4 },
  { userId: 10, productId: 3, ratingId: 3 },
  { userId: 12, productId: 3, ratingId: 4 },
  { userId: 15, productId: 3, ratingId: 4 },
  { userId: 16, productId: 3, ratingId: 5 },
  { userId: 17, productId: 3, ratingId: 5 },
  { userId: 18, productId: 3, ratingId: 2 },
  { userId: 9, productId: 5, ratingId: 3 },
  { userId: 5, productId: 5, ratingId: 5 },
  { userId: 6, productId: 5, ratingId: 1 },
  { userId: 12, productId: 5, ratingId: 5 },
  { userId: 15, productId: 5, ratingId: 4 },
  { userId: 16, productId: 5, ratingId: 5 },
  { userId: 17, productId: 5, ratingId: 5 },
  { userId: 18, productId: 5, ratingId: 2 },
  { userId: 2, productId: 6, ratingId: 4 },
  { userId: 3, productId: 6, ratingId: 4 },
  { userId: 4, productId: 6, ratingId: 4 },
  { userId: 5, productId: 6, ratingId: 5 },
  { userId: 6, productId: 6, ratingId: 3 },
  { userId: 7, productId: 6, ratingId: 4 },
  { userId: 8, productId: 6, ratingId: 4 },
  { userId: 9, productId: 6, ratingId: 4 },
  { userId: 10, productId: 6, ratingId: 3 },
  { userId: 11, productId: 6, ratingId: 3 },
  { userId: 2, productId: 7, ratingId: 4 },
  { userId: 3, productId: 7, ratingId: 4 },
  { userId: 4, productId: 7, ratingId: 4 },
  { userId: 5, productId: 7, ratingId: 5 },
  { userId: 6, productId: 7, ratingId: 3 },
  { userId: 7, productId: 7, ratingId: 4 },
  { userId: 8, productId: 7, ratingId: 4 },
  { userId: 9, productId: 7, ratingId: 4 },
  { userId: 10, productId: 7, ratingId: 3 },
  { userId: 11, productId: 7, ratingId: 3 },
  { userId: 2, productId: 8, ratingId: 5 },
  { userId: 3, productId: 8, ratingId: 5 },
  { userId: 4, productId: 8, ratingId: 3 },
  { userId: 5, productId: 8, ratingId: 5 },
  { userId: 6, productId: 8, ratingId: 2 },
  { userId: 7, productId: 8, ratingId: 3 },
  { userId: 8, productId: 8, ratingId: 5 },
  { userId: 9, productId: 8, ratingId: 5 },
  { userId: 10, productId: 8, ratingId: 1 },
  { userId: 11, productId: 8, ratingId: 1 },
  { userId: 12, productId: 8, ratingId: 2 },
  { userId: 13, productId: 8, ratingId: 5 },
  { userId: 14, productId: 8, ratingId: 5 },
  { userId: 15, productId: 8, ratingId: 4 },
  { userId: 16, productId: 8, ratingId: 4 },
  { userId: 17, productId: 8, ratingId: 5 },
  { userId: 18, productId: 8, ratingId: 5 },
  { userId: 19, productId: 8, ratingId: 3 },
  { userId: 20, productId: 8, ratingId: 3 },
  { userId: 10, productId: 9, ratingId: 3 },
  { userId: 11, productId: 9, ratingId: 3 },
  { userId: 12, productId: 9, ratingId: 4 },
  { userId: 13, productId: 9, ratingId: 5 },
  { userId: 14, productId: 9, ratingId: 3 },
  { userId: 15, productId: 9, ratingId: 3 },
  { userId: 16, productId: 9, ratingId: 2 },
  { userId: 17, productId: 9, ratingId: 1 },
  { userId: 18, productId: 9, ratingId: 3 },
  { userId: 19, productId: 9, ratingId: 4 },
  { userId: 20, productId: 9, ratingId: 3 },
  { userId: 2, productId: 11, ratingId: 4 },
  { userId: 3, productId: 11, ratingId: 4 },
  { userId: 4, productId: 11, ratingId: 3 },
  { userId: 5, productId: 11, ratingId: 5 },
  { userId: 6, productId: 11, ratingId: 4 },
  { userId: 10, productId: 11, ratingId: 4 },
  { userId: 11, productId: 11, ratingId: 2 },
  { userId: 12, productId: 11, ratingId: 1 },
  { userId: 13, productId: 11, ratingId: 4 },
  { userId: 14, productId: 11, ratingId: 4 },
  { userId: 15, productId: 11, ratingId: 3 },
  { userId: 16, productId: 11, ratingId: 2 },
  { userId: 17, productId: 11, ratingId: 5 },
  { userId: 18, productId: 11, ratingId: 4 },
  { userId: 19, productId: 11, ratingId: 4 },
  { userId: 20, productId: 11, ratingId: 4 },
  { userId: 5, productId: 13, ratingId: 5 },
  { userId: 6, productId: 13, ratingId: 5 },
  { userId: 10, productId: 13, ratingId: 5 },
  { userId: 11, productId: 13, ratingId: 5 },
  { userId: 12, productId: 13, ratingId: 3 },
  { userId: 13, productId: 13, ratingId: 5 },
  { userId: 14, productId: 13, ratingId: 5 },
  { userId: 15, productId: 13, ratingId: 3 },
  { userId: 16, productId: 13, ratingId: 5 },
  { userId: 17, productId: 13, ratingId: 5 },
  { userId: 18, productId: 13, ratingId: 5 },
  { userId: 19, productId: 13, ratingId: 4 },
  { userId: 20, productId: 13, ratingId: 4 },
  { userId: 5, productId: 16, ratingId: 4 },
  { userId: 6, productId: 16, ratingId: 4 },
  { userId: 10, productId: 16, ratingId: 4 },
  { userId: 11, productId: 16, ratingId: 4 },
  { userId: 12, productId: 16, ratingId: 4 },
  { userId: 13, productId: 16, ratingId: 4 },
  { userId: 14, productId: 16, ratingId: 4 },
  { userId: 15, productId: 16, ratingId: 3 },
  { userId: 16, productId: 16, ratingId: 4 },
  { userId: 17, productId: 16, ratingId: 4 },
  { userId: 18, productId: 16, ratingId: 2 },
  { userId: 19, productId: 16, ratingId: 2 },
  { userId: 20, productId: 16, ratingId: 1 },
  { userId: 2, productId: 18, ratingId: 5 },
  { userId: 3, productId: 18, ratingId: 5 },
  { userId: 5, productId: 18, ratingId: 5 },
  { userId: 6, productId: 18, ratingId: 5 },
  { userId: 10, productId: 18, ratingId: 5 },
  { userId: 11, productId: 18, ratingId: 5 },
  { userId: 12, productId: 18, ratingId: 5 },
  { userId: 13, productId: 18, ratingId: 5 },
  { userId: 14, productId: 18, ratingId: 3 },
  { userId: 15, productId: 18, ratingId: 5 },
  { userId: 16, productId: 18, ratingId: 4 },
  { userId: 17, productId: 18, ratingId: 4 },
  { userId: 18, productId: 18, ratingId: 5 },
  { userId: 19, productId: 18, ratingId: 5 },
  { userId: 20, productId: 18, ratingId: 3 },
  { userId: 2, productId: 10, ratingId: 5 },
  { userId: 3, productId: 10, ratingId: 5 },
  { userId: 5, productId: 10, ratingId: 5 },
  { userId: 6, productId: 10, ratingId: 5 },
  { userId: 10, productId: 10, ratingId: 5 },
  { userId: 11, productId: 10, ratingId: 5 },
  { userId: 12, productId: 10, ratingId: 5 },
  { userId: 13, productId: 10, ratingId: 5 },
  { userId: 14, productId: 10, ratingId: 3 },
  { userId: 15, productId: 10, ratingId: 5 },
  { userId: 19, productId: 12, ratingId: 4 },
  { userId: 20, productId: 12, ratingId: 4 },
  { userId: 2, productId: 12, ratingId: 4 },
  { userId: 3, productId: 12, ratingId: 4 },
  { userId: 5, productId: 12, ratingId: 4 },
  { userId: 6, productId: 12, ratingId: 4 },
  { userId: 10, productId: 12, ratingId: 3 },
  { userId: 11, productId: 12, ratingId: 4 },
  { userId: 12, productId: 12, ratingId: 5 },
  { userId: 13, productId: 12, ratingId: 4 },
  { userId: 14, productId: 12, ratingId: 2 },
  { userId: 15, productId: 12, ratingId: 5 },
  { userId: 10, productId: 15, ratingId: 4 },
  { userId: 11, productId: 15, ratingId: 4 },
  { userId: 12, productId: 15, ratingId: 4 },
  { userId: 13, productId: 15, ratingId: 4 },
  { userId: 14, productId: 15, ratingId: 4 },
  { userId: 15, productId: 15, ratingId: 4 },
  { userId: 2, productId: 14, ratingId: 3 },
  { userId: 3, productId: 14, ratingId: 4 },
  { userId: 4, productId: 14, ratingId: 5 },
  { userId: 5, productId: 14, ratingId: 4 },
  { userId: 6, productId: 14, ratingId: 2 },
  { userId: 7, productId: 14, ratingId: 5 },
  { userId: 10, productId: 14, ratingId: 4 },
  { userId: 11, productId: 14, ratingId: 4 },
  { userId: 12, productId: 14, ratingId: 4 },
  { userId: 13, productId: 14, ratingId: 4 },
  { userId: 14, productId: 14, ratingId: 4 },
  { userId: 15, productId: 14, ratingId: 4 },
];

export const discount_seed = [
  { productId: 4, productDiscount: 40 },
  { productId: 2, productDiscount: 35 },
  { productId: 1, productDiscount: 30 },
  { productId: 3, productDiscount: 25 },
  { productId: 5, productDiscount: 28 },
  { productId: 6, productDiscount: 18 },
  { productId: 7, productDiscount: 6 },
];

export const flashSales_seed = [
  { occasion: "Eid Al-fitr", endTime: "2026-03-25 23:59:59" },
];

export const flashSalesProducts_seed = [
  { flashSaleId: 1, productId: 4, productDiscount: 40 },
  { flashSaleId: 1, productId: 2, productDiscount: 35 },
  { flashSaleId: 1, productId: 1, productDiscount: 30 },
  { flashSaleId: 1, productId: 3, productDiscount: 25 },
  { flashSaleId: 1, productId: 5, productDiscount: 28 },
  { flashSaleId: 1, productId: 6, productDiscount: 18 },
  { flashSaleId: 1, productId: 7, productDiscount: 6 },
  { flashSaleId: 1, productId: 8, productDiscount: 15 },
];

export const wishList_seed = [
  { userId: 2, productId: 6 },
  { userId: 2, productId: 7 },
  { userId: 2, productId: 12 },
  { userId: 2, productId: 15 },
];
