export const users_seed = [
  {
    firstName: "admin",
    lastName: "one",
    email: "admin_1@example.com",
    phone: "123-456-7890",
    password: "Password@123",
    address: {
      building: "4B",
      street: "123 Main St",
      city: "Alexandria",
      country: "Egypt",
    },
    role: "admin",
  },
  {
    firstName: "user",
    lastName: "one",
    email: "user_1@example.com",
    phone: "11111111111",
    password: "Password@123",
    address: {
      building: "4B",
      street: "123 Main St",
      city: "Alexandria",
      country: "Egypt",
    },
    role: "user",
  },
  {
    firstName: "user",
    lastName: "two",
    email: "user_2@example.com",
    phone: "22222222222",
    password: "Password@123",
    address: {
      building: "4B",
      street: "123 Main St",
      city: "Alexandria",
      country: "Egypt",
    },
    role: "user",
  },
  {
    firstName: "user",
    lastName: "three",
    email: "user_3@example.com",
    phone: "33333333333",
    password: "Password@123",
    address: {
      building: "4B",
      street: "123 Main St",
      city: "Alexandria",
      country: "Egypt",
    },
    role: "user",
  },
  {
    firstName: "user",
    lastName: "four",
    email: "user_4@example.com",
    phone: "44444444444",
    password: "Password@123",
    address: {
      building: "4B",
      street: "123 Main St",
      city: "Alexandria",
      country: "Egypt",
    },
    role: "user",
  },
  {
    firstName: "user",
    lastName: "five",
    email: "user_5@example.com",
    phone: "55555555555",
    password: "Password@123",
    address: {
      building: "4B",
      street: "123 Main St",
      city: "Alexandria",
      country: "Egypt",
    },
    role: "user",
  },
  {
    firstName: "user",
    lastName: "six",
    email: "user_6@example.com",
    phone: "66666666666",
    password: "Password@123",
    address: {
      building: "4B",
      street: "123 Main St",
      city: "Alexandria",
      country: "Egypt",
    },
    role: "user",
  },
  {
    firstName: "user",
    lastName: "seven",
    email: "user_7@example.com",
    phone: "77777777777",
    password: "Password@123",
    address: {
      building: "4B",
      street: "123 Main St",
      city: "Alexandria",
      country: "Egypt",
    },
    role: "user",
  },
  {
    firstName: "user",
    lastName: "eight",
    email: "user_8@example.com",
    phone: "88888888888",
    password: "Password@123",
    address: {
      building: "4B",
      street: "123 Main St",
      city: "Alexandria",
      country: "Egypt",
    },
    role: "user",
  },
  {
    firstName: "user",
    lastName: "nine",
    email: "user_9@example.com",
    phone: "99999999999",
    password: "Password@123",
    address: {
      building: "4B",
      street: "123 Main St",
      city: "Alexandria",
      country: "Egypt",
    },
    role: "user",
  },
  {
    firstName: "user",
    lastName: "ten",
    email: "user_10@example.com",
    phone: "10101010101",
    password: "Password@123",
    address: {
      building: "4B",
      street: "123 Main St",
      city: "Alexandria",
      country: "Egypt",
    },
    role: "user",
  },
  {
    firstName: "user",
    lastName: "eleven",
    email: "user_11@example.com",
    phone: "01111111111",
    password: "Password@123",
    address: {
      building: "4B",
      street: "123 Main St",
      city: "Alexandria",
      country: "Egypt",
    },
    role: "user",
  },
  {
    firstName: "user",
    lastName: "twelve",
    email: "user_12@example.com",
    phone: "02222222222",
    password: "Password@123",
    address: {
      building: "4B",
      street: "123 Main St",
      city: "Alexandria",
      country: "Egypt",
    },
    role: "user",
  },
  {
    firstName: "user",
    lastName: "thirteen",
    email: "user_13@example.com",
    phone: "03333333333",
    password: "Password@123",
    address: {
      building: "4B",
      street: "123 Main St",
      city: "Alexandria",
      country: "Egypt",
    },
    role: "user",
  },
  {
    firstName: "user",
    lastName: "fourteen",
    email: "user_14@example.com",
    phone: "04444444444",
    password: "Password@123",
    address: {
      building: "4B",
      street: "123 Main St",
      city: "Alexandria",
      country: "Egypt",
    },
    role: "user",
  },
  {
    firstName: "user",
    lastName: "fifteen",
    email: "user_15@example.com",
    phone: "05555555555",
    password: "Password@123",
    address: {
      building: "4B",
      street: "123 Main St",
      city: "Alexandria",
      country: "Egypt",
    },
    role: "user",
  },
  {
    firstName: "user",
    lastName: "sixteen",
    email: "user_16@example.com",
    phone: "06666666666",
    password: "Password@123",
    address: {
      building: "4B",
      street: "123 Main St",
      city: "Alexandria",
      country: "Egypt",
    },
    role: "user",
  },
  {
    firstName: "user",
    lastName: "seventeen",
    email: "user_17@example.com",
    phone: "07777777777",
    password: "Password@123",
    address: {
      building: "4B",
      street: "123 Main St",
      city: "Alexandria",
      country: "Egypt",
    },
    role: "user",
  },
  {
    firstName: "user",
    lastName: "eighteen",
    email: "user_18@example.com",
    phone: "08888888888",
    password: "Password@123",
    address: {
      building: "4B",
      street: "123 Main St",
      city: "Alexandria",
      country: "Egypt",
    },
    role: "user",
  },
  {
    firstName: "user",
    lastName: "nineteen",
    email: "user_19@example.com",
    phone: "09999999999",
    password: "Password@123",
    address: {
      building: "4B",
      street: "123 Main St",
      city: "Alexandria",
      country: "Egypt",
    },
    role: "user",
  },
  {
    firstName: "user",
    lastName: "twenty",
    email: "user_20@example.com",
    phone: "00101010101",
    password: "Password@123",
    address: {
      building: "4B",
      street: "123 Main St",
      city: "Alexandria",
      country: "Egypt",
    },
    role: "user",
  },
];
